Fix direct access to ACPI tables on CONFIG_STRICT_DEVMEM=y  kernel
If the kernel is built with CONFIG_STRICT_DEVMEM=y access /dev/mem is limited and acpi_get_mmap call fails

Following call sequence leads to error

acpi_get_sig("ERDT")
  → checks /sys/firmware/acpi/tables/ERDT (doesn't exist)
  → calls acpi_get_mmap("ERDT")
      → calls acpi_get_rsdp()
          → calls acpi_rsdp_address_efi()
              → tries to read /sys/firmware/efi/systab
          → if that fails, calls acpi_rsdp_address_scan()
              → tries to mmap BIOS_RO_MEM_ADDR (0xE0000)
          → tries to mmap the found RSDP address

ERROR: Memory map failed, address=4007e014 size=36
ERROR: Memory mapping failed!
ERROR: Failed to obtain RSDP table!
WARN: Could not obtain ERDT table

As a workaround remove a call to acpi_get_mmap

Signed-off-by: Mikhail Malyshev <mike.malyshev@gmail.com>